In [2]:
import numpy as np

my_list = [1,2,3,4,5]
#create numpy array
np.array(my_list)


array([1, 2, 3, 4, 5])

In [5]:
#create zeros
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
#dtype keyword specifies type
x = np.zeros((3,4),dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [8]:
print('dtype: ',x.dtype)

dtype:  int64


In [10]:
#create ones
x = np.ones((3,4))
print(x)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
#create full of...
x = np.full((3,4),8)
print(x)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [13]:
#create identity matrix
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#create custom diagonals
x = np.diag((10,12,14,55))
print(x)

[[10  0  0  0]
 [ 0 12  0  0]
 [ 0  0 14  0]
 [ 0  0  0 55]]


In [16]:
#create integer ranges -  min,max,step (step defaults to 1)
x = np.arange(1,14,3)
print(x)

[ 1  4  7 10 13]


In [18]:
#watch out for finite floating point rounding issues, better to use linspace for floating point work
#inputs are start,stop,no of steps (defaults to 50)
x = np.linspace(0,25,10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [20]:
# can exclude endpoint
x = np.linspace(0,25,10, endpoint=False )
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [21]:
x = np.arange(20)
               

In [22]:
# reshape to any shape with the same no of elements

x = np.reshape(x,(10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [23]:
x = np.reshape(x,(4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [25]:
#pass one np function into the other
Y = np.arange(20).reshape(10,2)
print(Y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [28]:
# random numbers
# uses functions within the numpy module "random", hence the nested commands e.g. np.random.randlist

x=np.random.random((3,3))
print(x)

[[0.77276556 0.1788725  0.74176376]
 [0.17128044 0.84752032 0.30346914]
 [0.15482544 0.55687906 0.37554727]]


In [29]:
x=np.random.randint(4,15,(3,2))
print(x)

[[14  4]
 [ 8 12]
 [ 7  7]]


In [32]:
X=np.random.normal(0,0.1,size=(1000,1000))
print(X)

[[-0.12942073  0.03026457 -0.02105498 ...  0.0339989   0.02557192
  -0.19262102]
 [-0.1511015   0.01972945  0.02417528 ... -0.08229321 -0.07649414
  -0.07465683]
 [-0.24827586  0.06562266  0.07523014 ... -0.00178384 -0.16875656
   0.03205066]
 ...
 [-0.09297603 -0.07226517  0.09639611 ... -0.05644054  0.13453875
  -0.01500346]
 [-0.03197642  0.05017613 -0.06672434 ... -0.09137926 -0.02766239
   0.00233282]
 [-0.05239148  0.15628212  0.00387594 ... -0.22752966  0.21915272
   0.00986565]]


In [33]:
print('mean: ',X.mean())
print('std: ',X.std())
print('max: ',X.max())
print('min: ',X.min())
print('# positive: ',(X>0).sum())
print('# negative: ',(X<0).sum())

mean:  -8.041831919427411e-05
std:  0.0999957715105363
max:  0.4770417726651007
min:  -0.49280059179646796
# positive:  499496
# negative:  500504


In [1]:
import pandas as pd
!conda list pandas


# packages in environment at /home/darrengsteele/.pyenv/versions/anaconda3-2021.05/envs/studyenv:
#
# Name                    Version                   Build  Channel
pandas                    1.4.1                    pypi_0    pypi
